#!/bin/sh
set -eu
mariadb --protocol=socket -uroot -p"${MARIADB_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS gateway
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS authservice
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS userservice
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS mediaservice
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS postservice
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS feedservice
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS commentservice
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS keycloak
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${GATEWAY_DB_USERNAME}'@'%'
  IDENTIFIED BY '${GATEWAY_DB_PASSWORD}';
ALTER USER '${GATEWAY_DB_USERNAME}'@'%'
  IDENTIFIED BY '${GATEWAY_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON gateway.* TO '${GATEWAY_DB_USERNAME}'@'%';

CREATE USER IF NOT EXISTS '${AUTH_DB_USERNAME}'@'%'
  IDENTIFIED BY '${AUTH_DB_PASSWORD}';
ALTER USER '${AUTH_DB_USERNAME}'@'%'
  IDENTIFIED BY '${AUTH_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON authservice.* TO '${AUTH_DB_USERNAME}'@'%';

CREATE USER IF NOT EXISTS '${USER_DB_USERNAME}'@'%'
  IDENTIFIED BY '${USER_DB_PASSWORD}';
ALTER USER '${USER_DB_USERNAME}'@'%'
  IDENTIFIED BY '${USER_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON userservice.* TO '${USER_DB_USERNAME}'@'%';

CREATE USER IF NOT EXISTS '${POST_DB_USERNAME}'@'%'
  IDENTIFIED BY '${POST_DB_PASSWORD}';
ALTER USER '${POST_DB_USERNAME}'@'%'
  IDENTIFIED BY '${POST_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON postservice.* TO '${POST_DB_USERNAME}'@'%';

CREATE USER IF NOT EXISTS '${MEDIA_DB_USERNAME}'@'%'
  IDENTIFIED BY '${MEDIA_DB_PASSWORD}';
ALTER USER '${MEDIA_DB_USERNAME}'@'%'
  IDENTIFIED BY '${MEDIA_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON mediaservice.* TO '${MEDIA_DB_USERNAME}'@'%';

CREATE USER IF NOT EXISTS '${FEED_DB_USERNAME}'@'%'
  IDENTIFIED BY '${FEED_DB_PASSWORD}';
ALTER USER '${FEED_DB_USERNAME}'@'%'
  IDENTIFIED BY '${FEED_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON feedservice.* TO '${FEED_DB_USERNAME}'@'%';

CREATE USER IF NOT EXISTS '${COMMENT_DB_USERNAME}'@'%'
  IDENTIFIED BY '${COMMENT_DB_PASSWORD}';
ALTER USER '${COMMENT_DB_USERNAME}'@'%'
  IDENTIFIED BY '${COMMENT_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON commentservice.* TO '${COMMENT_DB_USERNAME}'@'%';

CREATE USER IF NOT EXISTS '${KEYCLOAK_DB_USERNAME}'@'%'
  IDENTIFIED BY '${KEYCLOAK_DB_PASSWORD}';
ALTER USER '${KEYCLOAK_DB_USERNAME}'@'%'
  IDENTIFIED BY '${KEYCLOAK_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON keycloak.* TO '${KEYCLOAK_DB_USERNAME}'@'%';

FLUSH PRIVILEGES;
SQL
