spring:
  cloud:
    function:
      definition: kafkaConsumer;kafkaProducer
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: localhost:9092
      bindings:
        friendshipEventsOut-out-0:
          destination: friendship-events-topic
          content-type: application/json
        friendRequestEventsOut-out-0:
          destination: friend-request-events
          content-type: application/json
        mediaCleanupOut-out-0:
          destination: media-cleanup-topic
          content-type: application/json
        binding-out-0:
          content-type: text/plain
          group: user-service
        kafkaConsumer-in-0:
          destination: sse-topic
          content-type: text/plain
          group: user-service
        kafkaProducer-out-0:
          content-type: text/plain
          group: user-service
