spring:
  cloud:
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: localhost:9092
      bindings:
        friendshipEventsOut-out-0:
          destination: friendship-events
          content-type: application/json
        friendRequestEventsOut-out-0:
          destination: friend-request-events
          content-type: application/json
        mediaCleanupOut-out-0:
          destination: media-cleanup-topic
          content-type: application/json
