configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDkzODY3Y2ZhNTY5NjMwMGEyNDQ5ZmY1YjEzMzBkODBjYWI2OGUyYTYwMTgwZTQ3M2U5MTUwZDI1N2M0YzkyMDc5NTI1NGI1OGVkOTUxZWE2YzMxMmUyYzRiOWQ5YWQ4OGQ0NzBhZjM2OTk4NTVmYTBiNWEwYzAyYmNhNmE4YmE=
