configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzY3M2ZjNTNiZjUxMWQ5ZWRmODI3NTYwYTdkMGY1Mjg4NWRmNGMxNzExM2FjOTliN2I4MThiN2MyYTZlN2UxNmRmYzk5MTBlMzAyZTk1NDdkZTYzNGE0NGYyNGRlYzZhMzBkNGZlMDNkZThlODhlNzQyNTU4NzRhYTMzOGY0YTc=
