configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGJlZGI0NzIxNmViMjM0NjdhYzk4MTdhZjQxNzZkZDdmZjk5OTM2NmYyMDAyNGM5NWExMTMzMDNmM2M0NGExNjFhYzc0ZmJiMzEyZTc5NTc5NjNjNmEzYmI0ODUzODUxNTgxMWJkNGE4ZTU3YjUxYzA4ODhiMGRhN2Q4NTI4MmM=
