package com.minh.fakebook.post.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostReactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostReactionAllPropertiesEquals(PostReaction expected, PostReaction actual) {
        assertPostReactionAutoGeneratedPropertiesEquals(expected, actual);
        assertPostReactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostReactionAllUpdatablePropertiesEquals(PostReaction expected, PostReaction actual) {
        assertPostReactionUpdatableFieldsEquals(expected, actual);
        assertPostReactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostReactionAutoGeneratedPropertiesEquals(PostReaction expected, PostReaction actual) {
        assertThat(actual)
            .as("Verify PostReaction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostReactionUpdatableFieldsEquals(PostReaction expected, PostReaction actual) {
        assertThat(actual)
            .as("Verify PostReaction relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getReactionType()).as("check reactionType").isEqualTo(expected.getReactionType()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostReactionUpdatableRelationshipsEquals(PostReaction expected, PostReaction actual) {
        assertThat(actual)
            .as("Verify PostReaction relationships")
            .satisfies(a -> assertThat(a.getPost()).as("check post").isEqualTo(expected.getPost()));
    }
}
