configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGRhZTliNzA4ZGU1YWRiZDMzYzU1YjNhN2FkMzA4NGZjMDMyNDEyMGMxZmUyZjhjYzBmZTRlZTMxZTE4ZWJiODI2MWQyMTliODc5YzM3OTEyN2I4ZmVmZWUyM2ZkNTRiNmQzOTNkZTFmNjI0ZTY5Mzk4ZTU5MjQ3MjQ2YTA5MjA=
