spring:
  cloud:
    function:
      definition: reactionEventConsumer;friendRequestEventConsumer;commentEventConsumer
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: localhost:9092
        bindings:
          reactionEventConsumer-in-0:
            consumer:
              enable-dlq: true
              dlq-name: post-reaction-events-gateway-dlt
          friendRequestEventConsumer-in-0:
            consumer:
              enable-dlq: true
              dlq-name: friend-request-events-gateway-dlt
          commentEventConsumer-in-0:
            consumer:
              enable-dlq: true
              dlq-name: comment-events-gateway-dlt
      bindings:
        reactionEventConsumer-in-0:
          destination: post-reaction-events
          content-type: application/json
          group: gateway
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
        friendRequestEventConsumer-in-0:
          destination: friend-request-events
          content-type: application/json
          group: gateway
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
        commentEventConsumer-in-0:
          destination: comment-events
          content-type: application/json
          group: gateway
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0

