spring:
  cloud:
    function:
      definition: kafkaConsumer;kafkaProducer;reactionEventConsumer;friendRequestEventConsumer
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: localhost:9092
      bindings:
        binding-out-0:
          content-type: text/plain
          group: gateway
        kafkaConsumer-in-0:
          destination: sse-topic
          content-type: text/plain
          group: gateway
        kafkaProducer-out-0:
          content-type: text/plain
          group: gateway
        reactionEventConsumer-in-0:
          destination: post-reaction-events
          content-type: application/json
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
        friendRequestEventConsumer-in-0:
          destination: friend-request-events
          content-type: application/json
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
