configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWM1N2VmNjA3MTI2MTQ1YzE2MDJhYjJjYTk2NjBlZDE4YWE3NjMxMTVlNTA4YzRhZGRkOTRkNmFlZDc0OGM5YzZmZmMyYjc0M2ZiY2MzZGVmYTI3OThkOTdmNGI4ZWYyMDZlNzQyZWUwZmY4YTI1ZGQxMGEyZjNkMDM1ZGZiMjE=
