configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTA3M2U1NzYyNTRhYjI0MjM1MGZiNmE2ZjU2Yzc5MmMxZGFiMDVkMDRmZDA4MWU5NGIwODg1ZjFmOGQwZjA0YzJjODkyNjc4ZWQ2NDFkMzY1OGVlYzk3YzViYTVkODA0NThiMmZjYWVkMTg4ZDM3MWZjMTFlZWI2MmFlODNmNDQ=
