package com.minh.fakebook.comment.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommentReactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentReactionAllPropertiesEquals(CommentReaction expected, CommentReaction actual) {
        assertCommentReactionAutoGeneratedPropertiesEquals(expected, actual);
        assertCommentReactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentReactionAllUpdatablePropertiesEquals(CommentReaction expected, CommentReaction actual) {
        assertCommentReactionUpdatableFieldsEquals(expected, actual);
        assertCommentReactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentReactionAutoGeneratedPropertiesEquals(CommentReaction expected, CommentReaction actual) {
        assertThat(actual)
            .as("Verify CommentReaction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentReactionUpdatableFieldsEquals(CommentReaction expected, CommentReaction actual) {
        assertThat(actual)
            .as("Verify CommentReaction relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getReactionType()).as("check reactionType").isEqualTo(expected.getReactionType()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentReactionUpdatableRelationshipsEquals(CommentReaction expected, CommentReaction actual) {
        assertThat(actual)
            .as("Verify CommentReaction relationships")
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()));
    }
}
