package com.minh.fakebook.comment.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostCacheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCacheAllPropertiesEquals(PostCache expected, PostCache actual) {
        assertPostCacheAutoGeneratedPropertiesEquals(expected, actual);
        assertPostCacheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCacheAllUpdatablePropertiesEquals(PostCache expected, PostCache actual) {
        assertPostCacheUpdatableFieldsEquals(expected, actual);
        assertPostCacheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCacheAutoGeneratedPropertiesEquals(PostCache expected, PostCache actual) {
        assertThat(actual)
            .as("Verify PostCache auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCacheUpdatableFieldsEquals(PostCache expected, PostCache actual) {
        assertThat(actual)
            .as("Verify PostCache relevant properties")
            .satisfies(a -> assertThat(a.getAuthorId()).as("check authorId").isEqualTo(expected.getAuthorId()))
            .satisfies(a -> assertThat(a.getVisibility()).as("check visibility").isEqualTo(expected.getVisibility()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostCacheUpdatableRelationshipsEquals(PostCache expected, PostCache actual) {
        // empty method
    }
}
