logging:
  level:
    com.minh.fakebook.auth: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:${MARIADB_PORT:3307}/authservice?useLegacyDatetimeCode=false
    username: ${FAKEBOOK_DB_USERNAME:root}
    password: ${FAKEBOOK_DB_PASSWORD:}
  liquibase:
    contexts: dev, faker
