logging:
  level:
    com.minh.fakebook.feed: INFO

server:
  port: 8086

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: ${FAKEBOOK_DB_USERNAME}
    password: ${FAKEBOOK_DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  liquibase:
    contexts: prod
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${FAKEBOOK_OIDC_ISSUER_URI:}
        registration:
          internal:
            provider: oidc
            client-id: ${FAKEBOOK_OIDC_CLIENT_ID}
            client-secret: ${FAKEBOOK_OIDC_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid

jhipster:
  cache:
    redis:
      server: redis://${REDIS_HOST:redis}:${REDIS_PORT:6379}
      cluster: false
