logging:
  level:
    com.minh.fakebook.feed: INFO

server:
  port: 8086

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: ${FAKEBOOK_DB_USERNAME}
    password: ${FAKEBOOK_DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  liquibase:
    contexts: prod

jhipster:
  cache:
    redis:
      server: redis://${REDIS_HOST:redis}:${REDIS_PORT:6379}
      cluster: false
