logging:
  level:
    com.minh.fakebook.post: INFO

server:
  port: 8083

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: ${FAKEBOOK_DB_USERNAME}
    password: ${FAKEBOOK_DB_PASSWORD}
  liquibase:
    contexts: prod
