logging:
  level:
    com.minh.fakebook.user: INFO

server:
  port: 8082

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://${MARIADB_HOST:mariadb}:${MARIADB_PORT:3306}/userservice?useLegacyDatetimeCode=false
    username: ${FAKEBOOK_DB_USERNAME}
    password: ${FAKEBOOK_DB_PASSWORD}
  liquibase:
    contexts: prod
