logging:
  level:
    com.minh.fakebook.user: INFO

server:
  port: 8082

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: ${FAKEBOOK_DB_USERNAME}
    password: ${FAKEBOOK_DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  liquibase:
    contexts: prod
