package com.minh.fakebook.user.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FriendshipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipAllPropertiesEquals(Friendship expected, Friendship actual) {
        assertFriendshipAutoGeneratedPropertiesEquals(expected, actual);
        assertFriendshipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipAllUpdatablePropertiesEquals(Friendship expected, Friendship actual) {
        assertFriendshipUpdatableFieldsEquals(expected, actual);
        assertFriendshipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipAutoGeneratedPropertiesEquals(Friendship expected, Friendship actual) {
        assertThat(actual)
            .as("Verify Friendship auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipUpdatableFieldsEquals(Friendship expected, Friendship actual) {
        assertThat(actual)
            .as("Verify Friendship relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendshipUpdatableRelationshipsEquals(Friendship expected, Friendship actual) {
        assertThat(actual)
            .as("Verify Friendship relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getFriend()).as("check friend").isEqualTo(expected.getFriend()));
    }
}
