package com.minh.fakebook.user.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FriendRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendRequestAllPropertiesEquals(FriendRequest expected, FriendRequest actual) {
        assertFriendRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertFriendRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendRequestAllUpdatablePropertiesEquals(FriendRequest expected, FriendRequest actual) {
        assertFriendRequestUpdatableFieldsEquals(expected, actual);
        assertFriendRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendRequestAutoGeneratedPropertiesEquals(FriendRequest expected, FriendRequest actual) {
        assertThat(actual)
            .as("Verify FriendRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendRequestUpdatableFieldsEquals(FriendRequest expected, FriendRequest actual) {
        assertThat(actual)
            .as("Verify FriendRequest relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getRespondedAt()).as("check respondedAt").isEqualTo(expected.getRespondedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendRequestUpdatableRelationshipsEquals(FriendRequest expected, FriendRequest actual) {
        assertThat(actual)
            .as("Verify FriendRequest relationships")
            .satisfies(a -> assertThat(a.getSender()).as("check sender").isEqualTo(expected.getSender()))
            .satisfies(a -> assertThat(a.getReceiver()).as("check receiver").isEqualTo(expected.getReceiver()));
    }
}
