spring:
  cloud:
    function:
      definition: processPostEvent;kafkaConsumer;kafkaProducer
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: localhost:9092
      bindings:
        processPostEvent-in-0:
          destination: post-events
          content-type: text/plain
          group: comment-service-post-sync
        binding-out-0:
          content-type: text/plain
          group: comment-service
        kafkaConsumer-in-0:
          destination: sse-topic
          content-type: text/plain
          group: comment-service
        kafkaProducer-out-0:
          content-type: text/plain
          group: comment-service
