spring:
  cloud:
    function:
      definition: processMediaCleanup;kafkaConsumer;kafkaProducer
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: localhost:9092
      bindings:
        processMediaCleanup-in-0:
          destination: media-cleanup-topic
          content-type: application/json
          group: media-service
        binding-out-0:
          content-type: text/plain
          group: media-service
        kafkaConsumer-in-0:
          destination: sse-topic
          content-type: text/plain
          group: media-service
        kafkaProducer-out-0:
          content-type: text/plain
          group: media-service

