spring:
  cloud:
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: localhost:9092
          enable-observation: true
      bindings:
        mediaCleanupOut-out-0:
          destination: media-cleanup-topic
          content-type: application/json
          producer:
            use-native-encoding: true
